#! /bin/sh
# /etc/init.d/garagedoor

### BEGIN INIT INFO
# Provides:          sidelight
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin


do_start () {
	# start the side light python application
	export LIBRATOKEY='put-in-the-real-key-here'
	/home/pi/autolight/securitylight.py >/dev/null 2>&1 &
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload|stop)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
